version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Web/LAHistoricalMarkers.Web/Dockerfile
    ports:
      - "80:5001"
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password01!"
      ACCEPT_EULA: "Y"
