name: Build and Deploy Functions
on:
  workflow_dispatch:

jobs:
  migrate-sql:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SQL_CREDENTIALS }}
      - uses: azure/sql-action@v1
          with:
            server-name: awebre-sql-prod
            connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
            sql-file: './Migrations/InitialMigration.sql'
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install DotNet
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-versions: "5.0.203"
      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh
        run: |
          pushd './Functions'
          dotnet build --configuration Release --output ./output
          popd
      - name: Deploy Functions
        uses: Azure/functions-action@v1.3.2
        with:
          app-name: la-historical-markers-prod
          package: "Functions/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
